apiVersion: "operators.coreos.com/v1"
kind: "CatalogSource"
metadata:
  name: "community-operators"
  namespace: "openshift-marketplace"
spec:
  sourceType: grpc
  image: quay.io/openshift-community-operators/catalog:latest
  displayName: "Community Operators"
  publisher: "Red Hat"
  priority: -400
  updateStrategy:
    registryPoll:
      interval: 10m
